source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

abstract_target 'NoticeWindowPods' do
  use_frameworks!

  pod "NoticeWindow", :path => "../"

  target 'NoticeWindow_Example' do
  end
  
  target 'NoticeWindow_Tests' do
  end

end
