source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NoticeWindow_Example', :exclusive => true do
  pod "NoticeWindow", :path => "../"
end

target 'NoticeWindow_Tests', :exclusive => true do
  pod "NoticeWindow", :path => "../"

  
end
